
-- Tài khoản Hội đồng đánh giá
CREATE TABLE UserHDDG (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  username VARCHAR(255),
  password VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(20),
  address TEXT,
  permission VARCHAR(20),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tài khoản Đơn vị báo cáo
CREATE TABLE UserDVBC (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  username VARCHAR(255),
  password VARCHAR(255),
  email VARCHAR(255),
  phone VARCHAR(20),
  address TEXT,
  id_DVBC INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Các bài báo cáo
CREATE TABLE BaoCao(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ten_bao_cao VARCHAR(255) NOT NULL,
  noi_dung TEXT,
  id_DVBC INT NOT NULL,
  kieu_bao_cao VARCHAR(20) NOT NULL,
  danh_gia VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Chi tiết về báo cáo. tiêu chuẩn, tiêu chí, minh chứng
CREATE TABLE ChiTietBaoCao(
  id_bao_cao INT NOT NULL,
  id_tieu_chi INT NOT NULL,
  id_minh_chung INT NOT NULL
);

-- Thông tin về các đơn vị báo cáo
CREATE TABLE DVBC (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ten_dvbc VARCHAR(255) NOT NULL,
  phone VARCHAR(20) DEFAULT NULL,
  address TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Thông tin về các chương trình đào tạo
CREATE TABLE CTDT (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ten_ctdt VARCHAR(255) NOT NULL,
  id_DVBC INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Minh chứng
CREATE TABLE MinhChung (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ten_minh_chung VARCHAR(255) NOT NULL,
  kieu_minh_chung VARCHAR(20) NOT NULL,
  noi_dung TEXT,
  ten_dvbc INT NOT NULL,
  dia_diem_phat_hanh VARCHAR(255) NOT NULL,
  ngay_phat_hanh TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ma_minh_chung VARCHAR(20) NOT NULL,
  file TEXT DEFAULT NULL,
  hash_file TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tiêu chuẩn
CREATE TABLE TieuChuan(
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ten_tieu_chuan  VARCHAR(255) NOT NULL,
  noi_dung TEXT,
  loai_tieu_chuan VARCHAR(20) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Tiêu chí
CREATE TABLE TieuChi (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  ten_tieu_chi VARCHAR(255) NOT NULL,
  loai_tieu_chi VARCHAR(20) NOT NULL,
  id_tieu_chuan INT NOT NULL,
  noi_dung TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


ALTER TABLE ChiTietBaoCao ADD CONSTRAINT fk_proof FOREIGN KEY (id_minh_chung) REFERENCES MinhChung (id);
ALTER TABLE ChiTietBaoCao ADD CONSTRAINT fk_report FOREIGN KEY (id_bao_cao) REFERENCES BaoCao (id);
ALTER TABLE ChiTietBaoCao ADD CONSTRAINT fk_criteria FOREIGN KEY (id_tieu_chi) REFERENCES TieuChi (id);

ALTER TABLE TieuChi ADD CONSTRAINT fk_standard_criteria FOREIGN KEY (id_tieu_chuan) REFERENCES TieuChuan(id);

ALTER TABLE UserDVBC ADD CONSTRAINT fk_report_ei FOREIGN KEY (id_DVBC) REFERENCES DVBC(id);
ALTER TABLE CTDT ADD CONSTRAINT fk_sc_ei FOREIGN KEY (id_DVBC) REFERENCES CTDT(id);
